import { test, expect, type Page } from '@playwright/test'

async function open(page: Page) {
  await page.goto('/')
  await expect(page.getByLabel('Agent', { exact: true })).toHaveValue('Research')
}

async function send(page: Page, message: string) {
  await page.getByRole('textbox', { name: 'Message', exact: true }).fill(message)
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
}

test('Default-only catalogue keeps host and agent selection usable', async ({ page }, testInfo) => {
  await page.route('**/api/vendors', async route => {
    const response = await route.fetch()
    const catalogue = await response.json() as { vendors: { key: string }[] }
    await route.fulfill({ response, json: {
      ...catalogue, vendors: catalogue.vendors.filter(vendor => vendor.key === 'default'),
    } })
  })
  await open(page)
  const host = page.getByLabel('Host', { exact: true })
  await expect(host).toHaveValue('default')
  await expect(host.locator('option')).toHaveText(['Default'])
  await page.getByLabel('Agent', { exact: true }).selectOption('Chat')
  await expect(page.getByLabel('Agent', { exact: true })).toHaveValue('Chat')
  await expect(host).toHaveValue('default')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('default-only.png'), fullPage: true })
})

test('repository link opens GitHub separately without losing the draft', async ({ page, context }, testInfo) => {
  const repository = 'https://github.com/o-viken/agenticlab'
  await context.route(repository, route => route.fulfill({ contentType: 'text/html', body: '<title>Agentic Lab on GitHub</title>' }))
  await open(page)
  const message = page.getByRole('textbox', { name: 'Message', exact: true })
  await message.fill('Keep this draft')
  const link = page.getByRole('link', { name: 'View Agentic Lab on GitHub (opens in a new tab)', exact: true })
  await expect(link).toBeVisible()
  await expect(link).toHaveAttribute('href', repository)
  await expect(link).toHaveAttribute('target', '_blank')
  await expect(link).toHaveAttribute('rel', 'noopener noreferrer')
  expect((await page.request.get('/github-mark.svg')).ok()).toBe(true)
  await link.focus()
  await expect(link).toBeFocused()
  const opened = page.waitForEvent('popup')
  await page.keyboard.press('Enter')
  const popup = await opened
  await expect(popup).toHaveURL(repository)
  await popup.close()
  await expect(message).toHaveValue('Keep this draft')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  const brand = await page.getByRole('link', { name: 'Agentic Lab home' }).boundingBox()
  const target = await link.boundingBox()
  expect(target!.x).toBeGreaterThanOrEqual(brand!.x + brand!.width)
  await page.getByRole('banner').screenshot({ path: testInfo.outputPath('github-header.png') })
})

test('manual execution, two tools, history and reset work through the BFF', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await open(page)
  await expect(page.getByLabel('Agent', { exact: true }).locator('option')).toHaveCount(3)
  await page.screenshot({ path: testInfo.outputPath('empty.png'), fullPage: true })
  await page.getByRole('button', { name: 'Manual', exact: true }).click()
  await send(page, 'Explain agents')
  await expect(page.getByRole('status')).toHaveText('Waiting for Next')
  await expect(page.getByRole('button', { name: 'Next step' })).toBeEnabled()
  await expect(page.getByLabel('Host', { exact: true })).toBeDisabled()
  const geometry = await page.locator('[data-node="host"]').boundingBox()
  for (let step = 1; step <= 10; step++) {
    await page.getByRole('button', { name: 'Next step' }).click()
    await expect(page.getByRole('region', { name: 'Run activity' }).locator('li')).toHaveCount(step)
    if (step === 6) await expect(page.getByText('SearchWiki', { exact: true })).toBeVisible()
  }
  await expect(page.getByRole('status')).toHaveText('Complete')
  await expect(page.getByRole('log')).toContainText('This is answer 1.')
  await expect(page.getByRole('log').getByText('An agent combines a host with a model.', { exact: true })).toHaveCount(1)
  const after = await page.locator('[data-node="host"]').boundingBox()
  expect(after?.width).toBe(geometry?.width)
  expect(after?.height).toBe(geometry?.height)
  await page.getByRole('button', { name: 'Auto', exact: true }).click()
  await send(page, 'Follow-up')
  await expect(page.getByRole('log')).toContainText('This is answer 2.')
  await expect(page.getByRole('status')).toHaveText('Complete')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('complete.png'), fullPage: true })
  await page.getByRole('button', { name: 'New conversation' }).click()
  await expect(page.getByRole('heading', { name: 'A new conversation' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Run activity' }).locator('li')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('host changes start fresh conversations while agent changes preserve history', async ({ page }, testInfo) => {
  const conversations: string[] = []
  const resets: string[] = []
  page.on('request', request => {
    if (request.url().endsWith('/api/chat/stream')) conversations.push(request.postDataJSON().conversationId)
    if (request.url().endsWith('/api/chat/reset')) resets.push(request.postDataJSON().conversationId)
  })
  await open(page)
  await send(page, 'First conversation')
  await expect(page.getByRole('status')).toHaveText('Complete')
  const host = page.getByLabel('Host', { exact: true })
  await host.dispatchEvent('change')
  await page.getByLabel('Agent', { exact: true }).selectOption('Chat')
  await send(page, 'Agent-only follow-up')
  await expect(page.getByRole('log')).toContainText('This is answer 2.')
  expect(conversations[1]).toBe(conversations[0])
  expect(resets).toEqual([])
  const draft = page.getByRole('textbox', { name: 'Message', exact: true })
  await draft.fill('Keep this draft')
  await page.getByRole('button', { name: 'Manual', exact: true }).click()
  await host.selectOption('chatgpt')
  await expect(host).toHaveValue('chatgpt')
  await expect(page.getByLabel('Agent', { exact: true })).toHaveValue('Chat')
  await expect(page.getByRole('heading', { name: 'A new conversation' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Run activity' }).locator('li')).toHaveCount(0)
  await expect(draft).toHaveValue('Keep this draft')
  await expect(page.getByRole('button', { name: 'Manual', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(resets).toEqual([conversations[0]])
  await page.screenshot({ path: testInfo.outputPath('vendor-reset.png'), fullPage: true })
  await page.getByRole('button', { name: 'Auto', exact: true }).click()
  await send(page, 'Fresh vendor')
  await expect(page.getByRole('log')).toContainText('This is answer 1.')
  expect(conversations[2]).not.toBe(conversations[0])
  await host.selectOption('default')
  await expect(host).toHaveValue('default')
  await expect(page.getByLabel('Agent', { exact: true })).toHaveValue('Research')
  await send(page, 'Back again')
  await expect(page.getByRole('log')).toContainText('This is answer 1.')
  expect(new Set([conversations[0], conversations[2], conversations[3]]).size).toBe(3)
  expect(resets).toEqual([conversations[0], conversations[2]])
})

test('a failed host reset preserves selection and history and allows retry', async ({ page }) => {
  await open(page)
  await send(page, 'Keep this conversation')
  await expect(page.getByRole('status')).toHaveText('Complete')
  const draft = page.getByRole('textbox', { name: 'Message', exact: true })
  await draft.fill('Keep this draft')
  let release!: () => void
  const pending = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/chat/reset', async route => {
    await pending
    await route.fulfill({ status: 503, contentType: 'application/problem+json', body: '{"title":"Reset unavailable"}' })
  })
  const host = page.getByLabel('Host', { exact: true })
  await host.selectOption('chatgpt')
  await expect(host).toBeDisabled()
  await expect(page.getByLabel('Agent', { exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeDisabled()
  release()
  await expect(page.getByRole('alert')).toContainText('Reset unavailable')
  await expect(host).toHaveValue('default')
  await expect(host).toBeEnabled()
  await expect(page.getByLabel('Agent', { exact: true })).toHaveValue('Research')
  await expect(page.getByRole('log')).toContainText('This is answer 1.')
  await expect(draft).toHaveValue('Keep this draft')
  await page.unroute('**/api/chat/reset')
  await host.selectOption('chatgpt')
  await expect(host).toHaveValue('chatgpt')
  await expect(page.getByRole('heading', { name: 'A new conversation' })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('pause, resume, mode changes and stop do not lose the draft', async ({ page }) => {
  await open(page)
  await send(page, 'Pause this')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Paused')
  await page.getByRole('textbox', { name: 'Message', exact: true }).fill('Unsent draft')
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await page.getByRole('button', { name: 'Manual', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Waiting for Next')
  await page.getByRole('button', { name: 'Stop run' }).click()
  await expect(page.getByRole('status')).toHaveText('Stopped')
  await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toHaveValue('Unsent draft')
  await expect(page.getByLabel('Agent', { exact: true })).toBeEnabled()
})

test('question, interruption, error and tool-less chat have honest states', async ({ page }) => {
  await open(page)
  await page.getByLabel('Agent', { exact: true }).selectOption('Question')
  await send(page, 'Ask me')
  await expect(page.getByRole('status')).toHaveText('Waiting for you')
  await page.getByRole('textbox', { name: 'Which topic should I use?' }).fill('Tool use')
  await page.getByRole('button', { name: 'Send answer' }).click()
  await expect(page.getByRole('log')).toContainText('You chose: Tool use')
  await page.getByRole('button', { name: 'New conversation' }).click()
  await page.getByLabel('Host', { exact: true }).selectOption('chatgpt')
  await expect(page.getByLabel('Agent', { exact: true })).toHaveValue('Chat')
  await send(page, 'interrupt')
  await expect(page.getByRole('status')).toHaveText('Interrupted')
  await expect(page.getByRole('alert')).toContainText('before a final answer')
  await send(page, 'error')
  await expect(page.getByRole('status')).toHaveText('Failed')
  await expect(page.getByRole('alert')).toContainText('upstream run failed')
  await send(page, 'A normal question')
  await expect(page.getByRole('status')).toHaveText('Complete')
  await expect(page.locator('[data-node="tools"]')).toContainText('No tools')
})

test('keyboard, reduced motion and unavailable catalog are usable', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await open(page)
  await page.getByRole('button', { name: 'Manual', exact: true }).focus()
  await page.keyboard.press('Space')
  await expect(page.getByRole('button', { name: 'Manual', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const message = page.getByRole('textbox', { name: 'Message', exact: true })
  await message.fill('first line')
  await message.press('Shift+Enter')
  await expect(message).toHaveValue('first line\n')
  await message.press('Enter')
  await expect(page.getByRole('status')).toHaveText('Waiting for Next')
  await page.getByRole('button', { name: 'Stop run' }).click()
  await page.route('**/api/agents', route => route.fulfill({ status: 502, contentType: 'application/problem+json', body: '{"title":"Gateway unavailable"}' }))
  await page.reload()
  await expect(page.getByRole('alert')).toContainText('Gateway unavailable')
  await page.unroute('**/api/agents')
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByLabel('Agent', { exact: true })).toHaveValue('Research')
})