<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c3642cfc-0469-40ad-aaf5-98d7900d35cc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheSeries.AiService\TheSeries.AiService.csproj" />
    <ProjectReference Include="..\TheSeries.A2AServer\TheSeries.A2AServer.csproj" />
    <ProjectReference Include="..\TheSeries.Console\TheSeries.Console.csproj" />
    <ProjectReference Include="..\TheSeries.McpServer\TheSeries.McpServer.csproj" />
    <ProjectReference Include="..\TheSeries.Web\TheSeries.Web.csproj" />
  </ItemGroup>

</Project>
